sudo: false
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
cache:
  bundler: true
  directories:
    - vendor/bundle
    - $HOME/.rvm
before_install:
  - openssl aes-256-cbc -K $encrypted_b34f33f06a22_key -iv $encrypted_b34f33f06a22_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key $USER@$SERVER_IP_ADDRESS -p $PORT pwd
install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
  - travis_retry bundle
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_RUBY_VERSION = "2.6.0" &&
    sed -i "2 i\REMOTE_FOR_DEPLOY=$REMOTE_FOR_DEPLOY_EDGE" ./deploy.sh && bash ./deploy.sh master
  - test $TRAVIS_BRANCH = "5-2-stable" &&
    sed -i "2 i\REMOTE_FOR_DEPLOY=$REMOTE_FOR_DEPLOY" ./deploy.sh && bash ./deploy.sh v5.2.2 stable
notifications:
  email: false
