sudo: false
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
cache: bundler
env:
  - USER=railsid
  - LATEST=v5.2.2
before_install:
  - openssl aes-256-cbc -K $encrypted_b34f33f06a22_key -iv $encrypted_b34f33f06a22_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key $USER@$SERVER_IP_ADDRESS -p $PORT pwd
  - rm Gemfile.lock -rf
  - travis_retry gem update --system
  - travis_retry gem install bundler
  - travis_retry bundle
install:
  - rake guides:generate ALL=1
  # - rake guides:generate ALL=1 RAILS_VERSION=$LATEST
  # - travis_retry rake guides:validate
branches:
  only:
    - master
after_success:
  - git clone $REMOTE_FOR_DEPLOY repository && cp output/* repository -R
  - cd repository && git add --all && git commit -m "Deploy!"
  - git push origin master
notifications:
  email: false
